from flask import Flask
import pyaudio
import wave
import subprocess
from datetime import datetime
from flask import render_template,jsonify,request
import os
import sys

app = Flask(__name__)

@app.route('/')
def index():
    return render_template('index.html')


@app.route('/chat',methods =['POST'])
def chat():
    user_name = request.form['text']
    print(user_name)
    CHUNK = 512
    FORMAT = pyaudio.paInt16
    CHANNELS = 1
    RATE = 44100
    RECORD_SECONDS = 5
    os.mkdir('Sound/{0}/'.format(user_name))
    WAVE_OUTPUT_FILENAME = "Sound/{0}/output_{1}.wav".format(user_name,datetime.now().time())
    print(WAVE_OUTPUT_FILENAME)

    p = pyaudio.PyAudio()

    stream = p.open(format=FORMAT,
                    channels=CHANNELS,
                    rate=RATE,
                    input=True,
                    frames_per_buffer=CHUNK)

    print("* recording")

    frames = []

    for i in range(0, int(RATE / CHUNK * RECORD_SECONDS)):
        data = stream.read(CHUNK)
        frames.append(data)

    print("* done recording")

    stream.stop_stream()
    stream.close()
    p.terminate()
    wf = wave.open(WAVE_OUTPUT_FILENAME, 'wb')
    wf.setnchannels(CHANNELS)
    wf.setsampwidth(p.get_sample_size(FORMAT))
    wf.setframerate(RATE)
    wf.writeframes(b''.join(frames))
    wf.close()
    system.call
    return render_template('Authenticate.html')


if __name__ == '__main__':
   app.run(debug=True)